name: Deploy to paulovtarkovdotnetapi-windows-dev

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: dotnet publish
        shell: pwsh
        run: dotnet publish -c Debug -o "${{env.DOTNET_ROOT}}/myapp"
    
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'paulovtarkovdotnetapi-windows-dev'
          slot-name: 'Production'
          package: "${{env.DOTNET_ROOT}}/myapp"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_6747DC01DFE747BA9F79232187AB4FA3 }}
